version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/taytebass/taytebass/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  button:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # w = Button ( master, option=value, ... )
          

workflows:
  my-custom-workflow:
    jobs:
      - button